[book]
authors = ["Atum"]
language = "en"
src = "src"
title = "AgentMemoryBook"
description = "A comprehensive guide to understanding how SOTA agent memory systems work"

[output.html]
default-theme = "light"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/A7um/AgentMemoryBook"
edit-url-template = "https://github.com/A7um/AgentMemoryBook/edit/main/src/{path}"
site-url = "/AgentMemoryBook/"
print = { enable = false }

[output.html.search]
enable = false
